version: "3"

tasks:
  default:
    desc: "Show task list"
    cmds:
      - task -l

  bin:chmod:
    desc: "Ensure .bin scripts are executable"
    cmds:
      - test -d .bin && ls .bin >/dev/null 2>&1 && chmod +x .bin/* || true

  doctor:
    desc: "Check required commands"
    deps: [bin:chmod]
    cmds:
      - ./.bin/doctor

  sync:
    desc: "Sync local ~/.config -> repo"
    deps: [bin:chmod]
    cmds:
      - ./.bin/sync

  apply:
    desc: "Apply repo -> local ~/.config"
    deps: [bin:chmod]
    cmds:
      - ./.bin/apply
